<?php

namespace Database\Seeders;

use App\Models\WilCity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WilCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $wil_cities = [
            ['id' => '1101', 'wil_province_id' => '11', 'name' => 'KAB. ACEH SELATAN',],
            ['id' => '1102', 'wil_province_id' => '11', 'name' => 'KAB. ACEH TENGGARA',],
            ['id' => '1103', 'wil_province_id' => '11', 'name' => 'KAB. ACEH TIMUR',],
            ['id' => '1104', 'wil_province_id' => '11', 'name' => 'KAB. ACEH TENGAH',],
            ['id' => '1105', 'wil_province_id' => '11', 'name' => 'KAB. ACEH BARAT',],
            ['id' => '1106', 'wil_province_id' => '11', 'name' => 'KAB. ACEH BESAR',],
            ['id' => '1107', 'wil_province_id' => '11', 'name' => 'KAB. PIDIE',],
            ['id' => '1108', 'wil_province_id' => '11', 'name' => 'KAB. ACEH UTARA',],
            ['id' => '1109', 'wil_province_id' => '11', 'name' => 'KAB. SIMEULUE',],
            ['id' => '1110', 'wil_province_id' => '11', 'name' => 'KAB. ACEH SINGKIL',],
            ['id' => '1111', 'wil_province_id' => '11', 'name' => 'KAB. BIREUEN',],
            ['id' => '1112', 'wil_province_id' => '11', 'name' => 'KAB. ACEH BARAT DAYA',],
            ['id' => '1113', 'wil_province_id' => '11', 'name' => 'KAB. GAYO LUES',],
            ['id' => '1114', 'wil_province_id' => '11', 'name' => 'KAB. ACEH JAYA',],
            ['id' => '1115', 'wil_province_id' => '11', 'name' => 'KAB. NAGAN RAYA',],
            ['id' => '1116', 'wil_province_id' => '11', 'name' => 'KAB. ACEH TAMIANG',],
            ['id' => '1117', 'wil_province_id' => '11', 'name' => 'KAB. BENER MERIAH',],
            ['id' => '1118', 'wil_province_id' => '11', 'name' => 'KAB. PIDIE JAYA',],
            ['id' => '1171', 'wil_province_id' => '11', 'name' => 'KOTA BANDA ACEH',],
            ['id' => '1172', 'wil_province_id' => '11', 'name' => 'KOTA SABANG',],
            ['id' => '1173', 'wil_province_id' => '11', 'name' => 'KOTA LHOKSEUMAWE',],
            ['id' => '1174', 'wil_province_id' => '11', 'name' => 'KOTA LANGSA',],
            ['id' => '1175', 'wil_province_id' => '11', 'name' => 'KOTA SUBULUSSALAM',],
            ['id' => '1201', 'wil_province_id' => '12', 'name' => 'KAB. TAPANULI TENGAH',],
            ['id' => '1202', 'wil_province_id' => '12', 'name' => 'KAB. TAPANULI UTARA',],
            ['id' => '1203', 'wil_province_id' => '12', 'name' => 'KAB. TAPANULI SELATAN',],
            ['id' => '1204', 'wil_province_id' => '12', 'name' => 'KAB. NIAS',],
            ['id' => '1205', 'wil_province_id' => '12', 'name' => 'KAB. LANGKAT',],
            ['id' => '1206', 'wil_province_id' => '12', 'name' => 'KAB. KARO',],
            ['id' => '1207', 'wil_province_id' => '12', 'name' => 'KAB. DELI SERDANG',],
            ['id' => '1208', 'wil_province_id' => '12', 'name' => 'KAB. SIMALUNGUN',],
            ['id' => '1209', 'wil_province_id' => '12', 'name' => 'KAB. ASAHAN',],
            ['id' => '1210', 'wil_province_id' => '12', 'name' => 'KAB. LABUHANBATU',],
            ['id' => '1211', 'wil_province_id' => '12', 'name' => 'KAB. DAIRI',],
            ['id' => '1212', 'wil_province_id' => '12', 'name' => 'KAB. TOBA',],
            ['id' => '1213', 'wil_province_id' => '12', 'name' => 'KAB. MANDAILING NATAL',],
            ['id' => '1214', 'wil_province_id' => '12', 'name' => 'KAB. NIAS SELATAN',],
            ['id' => '1215', 'wil_province_id' => '12', 'name' => 'KAB. PAKPAK BHARAT',],
            ['id' => '1216', 'wil_province_id' => '12', 'name' => 'KAB. HUMBANG HASUNDUTAN',],
            ['id' => '1217', 'wil_province_id' => '12', 'name' => 'KAB. SAMOSIR',],
            ['id' => '1218', 'wil_province_id' => '12', 'name' => 'KAB. SERDANG BEDAGAI',],
            ['id' => '1219', 'wil_province_id' => '12', 'name' => 'KAB. BATU BARA',],
            ['id' => '1220', 'wil_province_id' => '12', 'name' => 'KAB. PADANG LAWAS UTARA',],
            ['id' => '1221', 'wil_province_id' => '12', 'name' => 'KAB. PADANG LAWAS',],
            ['id' => '1222', 'wil_province_id' => '12', 'name' => 'KAB. LABUHANBATU SELATAN',],
            ['id' => '1223', 'wil_province_id' => '12', 'name' => 'KAB. LABUHANBATU UTARA',],
            ['id' => '1224', 'wil_province_id' => '12', 'name' => 'KAB. NIAS UTARA',],
            ['id' => '1225', 'wil_province_id' => '12', 'name' => 'KAB. NIAS BARAT',],
            ['id' => '1271', 'wil_province_id' => '12', 'name' => 'KOTA MEDAN',],
            ['id' => '1272', 'wil_province_id' => '12', 'name' => 'KOTA PEMATANGSIANTAR',],
            ['id' => '1273', 'wil_province_id' => '12', 'name' => 'KOTA SIBOLGA',],
            ['id' => '1274', 'wil_province_id' => '12', 'name' => 'KOTA TANJUNG BALAI',],
            ['id' => '1275', 'wil_province_id' => '12', 'name' => 'KOTA BINJAI',],
            ['id' => '1276', 'wil_province_id' => '12', 'name' => 'KOTA TEBING TINGGI',],
            ['id' => '1277', 'wil_province_id' => '12', 'name' => 'KOTA PADANGSIDIMPUAN',],
            ['id' => '1278', 'wil_province_id' => '12', 'name' => 'KOTA GUNUNGSITOLI',],
            ['id' => '1301', 'wil_province_id' => '13', 'name' => 'KAB. PESISIR SELATAN',],
            ['id' => '1302', 'wil_province_id' => '13', 'name' => 'KAB. SOLOK',],
            ['id' => '1303', 'wil_province_id' => '13', 'name' => 'KAB. SIJUNJUNG',],
            ['id' => '1304', 'wil_province_id' => '13', 'name' => 'KAB. TANAH DATAR',],
            ['id' => '1305', 'wil_province_id' => '13', 'name' => 'KAB. PADANG PARIAMAN',],
            ['id' => '1306', 'wil_province_id' => '13', 'name' => 'KAB. AGAM',],
            ['id' => '1307', 'wil_province_id' => '13', 'name' => 'KAB. LIMA PULUH KOTA',],
            ['id' => '1308', 'wil_province_id' => '13', 'name' => 'KAB. PASAMAN',],
            ['id' => '1309', 'wil_province_id' => '13', 'name' => 'KAB. KEPULAUAN MENTAWAI',],
            ['id' => '1310', 'wil_province_id' => '13', 'name' => 'KAB. DHARMASRAYA',],
            ['id' => '1311', 'wil_province_id' => '13', 'name' => 'KAB. SOLOK SELATAN',],
            ['id' => '1312', 'wil_province_id' => '13', 'name' => 'KAB. PASAMAN BARAT',],
            ['id' => '1371', 'wil_province_id' => '13', 'name' => 'KOTA PADANG',],
            ['id' => '1372', 'wil_province_id' => '13', 'name' => 'KOTA SOLOK',],
            ['id' => '1373', 'wil_province_id' => '13', 'name' => 'KOTA SAWAHLUNTO',],
            ['id' => '1374', 'wil_province_id' => '13', 'name' => 'KOTA PADANG PANJANG',],
            ['id' => '1375', 'wil_province_id' => '13', 'name' => 'KOTA BUKITTINGGI',],
            ['id' => '1376', 'wil_province_id' => '13', 'name' => 'KOTA PAYAKUMBUH',],
            ['id' => '1377', 'wil_province_id' => '13', 'name' => 'KOTA PARIAMAN',],
            ['id' => '1401', 'wil_province_id' => '14', 'name' => 'KAB. KAMPAR',],
            ['id' => '1402', 'wil_province_id' => '14', 'name' => 'KAB. INDRAGIRI HULU',],
            ['id' => '1403', 'wil_province_id' => '14', 'name' => 'KAB. BENGKALIS',],
            ['id' => '1404', 'wil_province_id' => '14', 'name' => 'KAB. INDRAGIRI HILIR',],
            ['id' => '1405', 'wil_province_id' => '14', 'name' => 'KAB. PELALAWAN',],
            ['id' => '1406', 'wil_province_id' => '14', 'name' => 'KAB. ROKAN HULU',],
            ['id' => '1407', 'wil_province_id' => '14', 'name' => 'KAB. ROKAN HILIR',],
            ['id' => '1408', 'wil_province_id' => '14', 'name' => 'KAB. SIAK',],
            ['id' => '1409', 'wil_province_id' => '14', 'name' => 'KAB. KUANTAN SINGINGI',],
            ['id' => '1410', 'wil_province_id' => '14', 'name' => 'KAB. KEPULAUAN MERANTI',],
            ['id' => '1471', 'wil_province_id' => '14', 'name' => 'KOTA PEKANBARU',],
            ['id' => '1472', 'wil_province_id' => '14', 'name' => 'KOTA DUMAI',],
            ['id' => '1501', 'wil_province_id' => '15', 'name' => 'KAB. KERINCI',],
            ['id' => '1502', 'wil_province_id' => '15', 'name' => 'KAB. MERANGIN',],
            ['id' => '1503', 'wil_province_id' => '15', 'name' => 'KAB. SAROLANGUN',],
            ['id' => '1504', 'wil_province_id' => '15', 'name' => 'KAB. BATANGHARI',],
            ['id' => '1505', 'wil_province_id' => '15', 'name' => 'KAB. MUARO JAMBI',],
            ['id' => '1506', 'wil_province_id' => '15', 'name' => 'KAB. TANJUNG JABUNG BARAT',],
            ['id' => '1507', 'wil_province_id' => '15', 'name' => 'KAB. TANJUNG JABUNG TIMUR',],
            ['id' => '1508', 'wil_province_id' => '15', 'name' => 'KAB. BUNGO',],
            ['id' => '1509', 'wil_province_id' => '15', 'name' => 'KAB. TEBO',],
            ['id' => '1571', 'wil_province_id' => '15', 'name' => 'KOTA JAMBI',],
            ['id' => '1572', 'wil_province_id' => '15', 'name' => 'KOTA SUNGAI PENUH',],
            ['id' => '1601', 'wil_province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU',],
            ['id' => '1602', 'wil_province_id' => '16', 'name' => 'KAB. OGAN KOMERING ILIR',],
            ['id' => '1603', 'wil_province_id' => '16', 'name' => 'KAB. MUARA ENIM',],
            ['id' => '1604', 'wil_province_id' => '16', 'name' => 'KAB. LAHAT',],
            ['id' => '1605', 'wil_province_id' => '16', 'name' => 'KAB. MUSI RAWAS',],
            ['id' => '1606', 'wil_province_id' => '16', 'name' => 'KAB. MUSI BANYUASIN',],
            ['id' => '1607', 'wil_province_id' => '16', 'name' => 'KAB. BANYUASIN',],
            ['id' => '1608', 'wil_province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU TIMUR',],
            ['id' => '1609', 'wil_province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU SELATAN',],
            ['id' => '1610', 'wil_province_id' => '16', 'name' => 'KAB. OGAN ILIR',],
            ['id' => '1611', 'wil_province_id' => '16', 'name' => 'KAB. EMPAT LAWANG',],
            ['id' => '1612', 'wil_province_id' => '16', 'name' => 'KAB. PENUKAL ABAB LEMATANG ILIR',],
            ['id' => '1613', 'wil_province_id' => '16', 'name' => 'KAB. MUSI RAWAS UTARA',],
            ['id' => '1671', 'wil_province_id' => '16', 'name' => 'KOTA PALEMBANG',],
            ['id' => '1672', 'wil_province_id' => '16', 'name' => 'KOTA PAGAR ALAM',],
            ['id' => '1673', 'wil_province_id' => '16', 'name' => 'KOTA LUBUK LINGGAU',],
            ['id' => '1674', 'wil_province_id' => '16', 'name' => 'KOTA PRABUMULIH',],
            ['id' => '1701', 'wil_province_id' => '17', 'name' => 'KAB. BENGKULU SELATAN',],
            ['id' => '1702', 'wil_province_id' => '17', 'name' => 'KAB. REJANG LEBONG',],
            ['id' => '1703', 'wil_province_id' => '17', 'name' => 'KAB. BENGKULU UTARA',],
            ['id' => '1704', 'wil_province_id' => '17', 'name' => 'KAB. KAUR',],
            ['id' => '1705', 'wil_province_id' => '17', 'name' => 'KAB. SELUMA',],
            ['id' => '1706', 'wil_province_id' => '17', 'name' => 'KAB. MUKO MUKO',],
            ['id' => '1707', 'wil_province_id' => '17', 'name' => 'KAB. LEBONG',],
            ['id' => '1708', 'wil_province_id' => '17', 'name' => 'KAB. KEPAHIANG',],
            ['id' => '1709', 'wil_province_id' => '17', 'name' => 'KAB. BENGKULU TENGAH',],
            ['id' => '1771', 'wil_province_id' => '17', 'name' => 'KOTA BENGKULU',],
            ['id' => '1801', 'wil_province_id' => '18', 'name' => 'KAB. LAMPUNG SELATAN',],
            ['id' => '1802', 'wil_province_id' => '18', 'name' => 'KAB. LAMPUNG TENGAH',],
            ['id' => '1803', 'wil_province_id' => '18', 'name' => 'KAB. LAMPUNG UTARA',],
            ['id' => '1804', 'wil_province_id' => '18', 'name' => 'KAB. LAMPUNG BARAT',],
            ['id' => '1805', 'wil_province_id' => '18', 'name' => 'KAB. TULANG BAWANG',],
            ['id' => '1806', 'wil_province_id' => '18', 'name' => 'KAB. TANGGAMUS',],
            ['id' => '1807', 'wil_province_id' => '18', 'name' => 'KAB. LAMPUNG TIMUR',],
            ['id' => '1808', 'wil_province_id' => '18', 'name' => 'KAB. WAY KANAN',],
            ['id' => '1809', 'wil_province_id' => '18', 'name' => 'KAB. PESAWARAN',],
            ['id' => '1810', 'wil_province_id' => '18', 'name' => 'KAB. PRINGSEWU',],
            ['id' => '1811', 'wil_province_id' => '18', 'name' => 'KAB. MESUJI',],
            ['id' => '1812', 'wil_province_id' => '18', 'name' => 'KAB. TULANG BAWANG BARAT',],
            ['id' => '1813', 'wil_province_id' => '18', 'name' => 'KAB. PESISIR BARAT',],
            ['id' => '1871', 'wil_province_id' => '18', 'name' => 'KOTA BANDAR LAMPUNG',],
            ['id' => '1872', 'wil_province_id' => '18', 'name' => 'KOTA METRO',],
            ['id' => '1901', 'wil_province_id' => '19', 'name' => 'KAB. BANGKA',],
            ['id' => '1902', 'wil_province_id' => '19', 'name' => 'KAB. BELITUNG',],
            ['id' => '1903', 'wil_province_id' => '19', 'name' => 'KAB. BANGKA SELATAN',],
            ['id' => '1904', 'wil_province_id' => '19', 'name' => 'KAB. BANGKA TENGAH',],
            ['id' => '1905', 'wil_province_id' => '19', 'name' => 'KAB. BANGKA BARAT',],
            ['id' => '1906', 'wil_province_id' => '19', 'name' => 'KAB. BELITUNG TIMUR',],
            ['id' => '1971', 'wil_province_id' => '19', 'name' => 'KOTA PANGKAL PINANG',],
            ['id' => '2101', 'wil_province_id' => '21', 'name' => 'KAB. BINTAN',],
            ['id' => '2102', 'wil_province_id' => '21', 'name' => 'KAB. KARIMUN',],
            ['id' => '2103', 'wil_province_id' => '21', 'name' => 'KAB. NATUNA',],
            ['id' => '2104', 'wil_province_id' => '21', 'name' => 'KAB. LINGGA',],
            ['id' => '2105', 'wil_province_id' => '21', 'name' => 'KAB. KEPULAUAN ANAMBAS',],
            ['id' => '2171', 'wil_province_id' => '21', 'name' => 'KOTA BATAM',],
            ['id' => '2172', 'wil_province_id' => '21', 'name' => 'KOTA TANJUNG PINANG',],
            ['id' => '3101', 'wil_province_id' => '31', 'name' => 'KAB. ADM. KEP. SERIBU',],
            ['id' => '3171', 'wil_province_id' => '31', 'name' => 'KOTA ADM. JAKARTA PUSAT',],
            ['id' => '3172', 'wil_province_id' => '31', 'name' => 'KOTA ADM. JAKARTA UTARA',],
            ['id' => '3173', 'wil_province_id' => '31', 'name' => 'KOTA ADM. JAKARTA BARAT',],
            ['id' => '3174', 'wil_province_id' => '31', 'name' => 'KOTA ADM. JAKARTA SELATAN',],
            ['id' => '3175', 'wil_province_id' => '31', 'name' => 'KOTA ADM. JAKARTA TIMUR',],
            ['id' => '3201', 'wil_province_id' => '32', 'name' => 'KAB. BOGOR',],
            ['id' => '3202', 'wil_province_id' => '32', 'name' => 'KAB. SUKABUMI',],
            ['id' => '3203', 'wil_province_id' => '32', 'name' => 'KAB. CIANJUR',],
            ['id' => '3204', 'wil_province_id' => '32', 'name' => 'KAB. BANDUNG',],
            ['id' => '3205', 'wil_province_id' => '32', 'name' => 'KAB. GARUT',],
            ['id' => '3206', 'wil_province_id' => '32', 'name' => 'KAB. TASIKMALAYA',],
            ['id' => '3207', 'wil_province_id' => '32', 'name' => 'KAB. CIAMIS',],
            ['id' => '3208', 'wil_province_id' => '32', 'name' => 'KAB. KUNINGAN',],
            ['id' => '3209', 'wil_province_id' => '32', 'name' => 'KAB. CIREBON',],
            ['id' => '3210', 'wil_province_id' => '32', 'name' => 'KAB. MAJALENGKA',],
            ['id' => '3211', 'wil_province_id' => '32', 'name' => 'KAB. SUMEDANG',],
            ['id' => '3212', 'wil_province_id' => '32', 'name' => 'KAB. INDRAMAYU',],
            ['id' => '3213', 'wil_province_id' => '32', 'name' => 'KAB. SUBANG',],
            ['id' => '3214', 'wil_province_id' => '32', 'name' => 'KAB. PURWAKARTA',],
            ['id' => '3215', 'wil_province_id' => '32', 'name' => 'KAB. KARAWANG',],
            ['id' => '3216', 'wil_province_id' => '32', 'name' => 'KAB. BEKASI',],
            ['id' => '3217', 'wil_province_id' => '32', 'name' => 'KAB. BANDUNG BARAT',],
            ['id' => '3218', 'wil_province_id' => '32', 'name' => 'KAB. PANGANDARAN',],
            ['id' => '3271', 'wil_province_id' => '32', 'name' => 'KOTA BOGOR',],
            ['id' => '3272', 'wil_province_id' => '32', 'name' => 'KOTA SUKABUMI',],
            ['id' => '3273', 'wil_province_id' => '32', 'name' => 'KOTA BANDUNG',],
            ['id' => '3274', 'wil_province_id' => '32', 'name' => 'KOTA CIREBON',],
            ['id' => '3275', 'wil_province_id' => '32', 'name' => 'KOTA BEKASI',],
            ['id' => '3276', 'wil_province_id' => '32', 'name' => 'KOTA DEPOK',],
            ['id' => '3277', 'wil_province_id' => '32', 'name' => 'KOTA CIMAHI',],
            ['id' => '3278', 'wil_province_id' => '32', 'name' => 'KOTA TASIKMALAYA',],
            ['id' => '3279', 'wil_province_id' => '32', 'name' => 'KOTA BANJAR',],
            ['id' => '3301', 'wil_province_id' => '33', 'name' => 'KAB. CILACAP',],
            ['id' => '3302', 'wil_province_id' => '33', 'name' => 'KAB. BANYUMAS',],
            ['id' => '3303', 'wil_province_id' => '33', 'name' => 'KAB. PURBALINGGA',],
            ['id' => '3304', 'wil_province_id' => '33', 'name' => 'KAB. BANJARNEGARA',],
            ['id' => '3305', 'wil_province_id' => '33', 'name' => 'KAB. KEBUMEN',],
            ['id' => '3306', 'wil_province_id' => '33', 'name' => 'KAB. PURWOREJO',],
            ['id' => '3307', 'wil_province_id' => '33', 'name' => 'KAB. WONOSOBO',],
            ['id' => '3308', 'wil_province_id' => '33', 'name' => 'KAB. MAGELANG',],
            ['id' => '3309', 'wil_province_id' => '33', 'name' => 'KAB. BOYOLALI',],
            ['id' => '3310', 'wil_province_id' => '33', 'name' => 'KAB. KLATEN',],
            ['id' => '3311', 'wil_province_id' => '33', 'name' => 'KAB. SUKOHARJO',],
            ['id' => '3312', 'wil_province_id' => '33', 'name' => 'KAB. WONOGIRI',],
            ['id' => '3313', 'wil_province_id' => '33', 'name' => 'KAB. KARANGANYAR',],
            ['id' => '3314', 'wil_province_id' => '33', 'name' => 'KAB. SRAGEN',],
            ['id' => '3315', 'wil_province_id' => '33', 'name' => 'KAB. GROBOGAN',],
            ['id' => '3316', 'wil_province_id' => '33', 'name' => 'KAB. BLORA',],
            ['id' => '3317', 'wil_province_id' => '33', 'name' => 'KAB. REMBANG',],
            ['id' => '3318', 'wil_province_id' => '33', 'name' => 'KAB. PATI',],
            ['id' => '3319', 'wil_province_id' => '33', 'name' => 'KAB. KUDUS',],
            ['id' => '3320', 'wil_province_id' => '33', 'name' => 'KAB. JEPARA',],
            ['id' => '3321', 'wil_province_id' => '33', 'name' => 'KAB. DEMAK',],
            ['id' => '3322', 'wil_province_id' => '33', 'name' => 'KAB. SEMARANG',],
            ['id' => '3323', 'wil_province_id' => '33', 'name' => 'KAB. TEMANGGUNG',],
            ['id' => '3324', 'wil_province_id' => '33', 'name' => 'KAB. KENDAL',],
            ['id' => '3325', 'wil_province_id' => '33', 'name' => 'KAB. BATANG',],
            ['id' => '3326', 'wil_province_id' => '33', 'name' => 'KAB. PEKALONGAN',],
            ['id' => '3327', 'wil_province_id' => '33', 'name' => 'KAB. PEMALANG',],
            ['id' => '3328', 'wil_province_id' => '33', 'name' => 'KAB. TEGAL',],
            ['id' => '3329', 'wil_province_id' => '33', 'name' => 'KAB. BREBES',],
            ['id' => '3371', 'wil_province_id' => '33', 'name' => 'KOTA MAGELANG',],
            ['id' => '3372', 'wil_province_id' => '33', 'name' => 'KOTA SURAKARTA',],
            ['id' => '3373', 'wil_province_id' => '33', 'name' => 'KOTA SALATIGA',],
            ['id' => '3374', 'wil_province_id' => '33', 'name' => 'KOTA SEMARANG',],
            ['id' => '3375', 'wil_province_id' => '33', 'name' => 'KOTA PEKALONGAN',],
            ['id' => '3376', 'wil_province_id' => '33', 'name' => 'KOTA TEGAL',],
            ['id' => '3401', 'wil_province_id' => '34', 'name' => 'KAB. KULON PROGO',],
            ['id' => '3402', 'wil_province_id' => '34', 'name' => 'KAB. BANTUL',],
            ['id' => '3403', 'wil_province_id' => '34', 'name' => 'KAB. GUNUNGKIDUL',],
            ['id' => '3404', 'wil_province_id' => '34', 'name' => 'KAB. SLEMAN',],
            ['id' => '3471', 'wil_province_id' => '34', 'name' => 'KOTA YOGYAKARTA',],
            ['id' => '3501', 'wil_province_id' => '35', 'name' => 'KAB. PACITAN',],
            ['id' => '3502', 'wil_province_id' => '35', 'name' => 'KAB. PONOROGO',],
            ['id' => '3503', 'wil_province_id' => '35', 'name' => 'KAB. TRENGGALEK',],
            ['id' => '3504', 'wil_province_id' => '35', 'name' => 'KAB. TULUNGAGUNG',],
            ['id' => '3505', 'wil_province_id' => '35', 'name' => 'KAB. BLITAR',],
            ['id' => '3506', 'wil_province_id' => '35', 'name' => 'KAB. KEDIRI',],
            ['id' => '3507', 'wil_province_id' => '35', 'name' => 'KAB. MALANG',],
            ['id' => '3508', 'wil_province_id' => '35', 'name' => 'KAB. LUMAJANG',],
            ['id' => '3509', 'wil_province_id' => '35', 'name' => 'KAB. JEMBER',],
            ['id' => '3510', 'wil_province_id' => '35', 'name' => 'KAB. BANYUWANGI',],
            ['id' => '3511', 'wil_province_id' => '35', 'name' => 'KAB. BONDOWOSO',],
            ['id' => '3512', 'wil_province_id' => '35', 'name' => 'KAB. SITUBONDO',],
            ['id' => '3513', 'wil_province_id' => '35', 'name' => 'KAB. PROBOLINGGO',],
            ['id' => '3514', 'wil_province_id' => '35', 'name' => 'KAB. PASURUAN',],
            ['id' => '3515', 'wil_province_id' => '35', 'name' => 'KAB. SIDOARJO',],
            ['id' => '3516', 'wil_province_id' => '35', 'name' => 'KAB. MOJOKERTO',],
            ['id' => '3517', 'wil_province_id' => '35', 'name' => 'KAB. JOMBANG',],
            ['id' => '3518', 'wil_province_id' => '35', 'name' => 'KAB. NGANJUK',],
            ['id' => '3519', 'wil_province_id' => '35', 'name' => 'KAB. MADIUN',],
            ['id' => '3520', 'wil_province_id' => '35', 'name' => 'KAB. MAGETAN',],
            ['id' => '3521', 'wil_province_id' => '35', 'name' => 'KAB. NGAWI',],
            ['id' => '3522', 'wil_province_id' => '35', 'name' => 'KAB. BOJONEGORO',],
            ['id' => '3523', 'wil_province_id' => '35', 'name' => 'KAB. TUBAN',],
            ['id' => '3524', 'wil_province_id' => '35', 'name' => 'KAB. LAMONGAN',],
            ['id' => '3525', 'wil_province_id' => '35', 'name' => 'KAB. GRESIK',],
            ['id' => '3526', 'wil_province_id' => '35', 'name' => 'KAB. BANGKALAN',],
            ['id' => '3527', 'wil_province_id' => '35', 'name' => 'KAB. SAMPANG',],
            ['id' => '3528', 'wil_province_id' => '35', 'name' => 'KAB. PAMEKASAN',],
            ['id' => '3529', 'wil_province_id' => '35', 'name' => 'KAB. SUMENEP',],
            ['id' => '3571', 'wil_province_id' => '35', 'name' => 'KOTA KEDIRI',],
            ['id' => '3572', 'wil_province_id' => '35', 'name' => 'KOTA BLITAR',],
            ['id' => '3573', 'wil_province_id' => '35', 'name' => 'KOTA MALANG',],
            ['id' => '3574', 'wil_province_id' => '35', 'name' => 'KOTA PROBOLINGGO',],
            ['id' => '3575', 'wil_province_id' => '35', 'name' => 'KOTA PASURUAN',],
            ['id' => '3576', 'wil_province_id' => '35', 'name' => 'KOTA MOJOKERTO',],
            ['id' => '3577', 'wil_province_id' => '35', 'name' => 'KOTA MADIUN',],
            ['id' => '3578', 'wil_province_id' => '35', 'name' => 'KOTA SURABAYA',],
            ['id' => '3579', 'wil_province_id' => '35', 'name' => 'KOTA BATU',],
            ['id' => '3601', 'wil_province_id' => '36', 'name' => 'KAB. PANDEGLANG',],
            ['id' => '3602', 'wil_province_id' => '36', 'name' => 'KAB. LEBAK',],
            ['id' => '3603', 'wil_province_id' => '36', 'name' => 'KAB. TANGERANG',],
            ['id' => '3604', 'wil_province_id' => '36', 'name' => 'KAB. SERANG',],
            ['id' => '3671', 'wil_province_id' => '36', 'name' => 'KOTA TANGERANG',],
            ['id' => '3672', 'wil_province_id' => '36', 'name' => 'KOTA CILEGON',],
            ['id' => '3673', 'wil_province_id' => '36', 'name' => 'KOTA SERANG',],
            ['id' => '3674', 'wil_province_id' => '36', 'name' => 'KOTA TANGERANG SELATAN',],
            ['id' => '5101', 'wil_province_id' => '51', 'name' => 'KAB. JEMBRANA',],
            ['id' => '5102', 'wil_province_id' => '51', 'name' => 'KAB. TABANAN',],
            ['id' => '5103', 'wil_province_id' => '51', 'name' => 'KAB. BADUNG',],
            ['id' => '5104', 'wil_province_id' => '51', 'name' => 'KAB. GIANYAR',],
            ['id' => '5105', 'wil_province_id' => '51', 'name' => 'KAB. KLUNGKUNG',],
            ['id' => '5106', 'wil_province_id' => '51', 'name' => 'KAB. BANGLI',],
            ['id' => '5107', 'wil_province_id' => '51', 'name' => 'KAB. KARANGASEM',],
            ['id' => '5108', 'wil_province_id' => '51', 'name' => 'KAB. BULELENG',],
            ['id' => '5171', 'wil_province_id' => '51', 'name' => 'KOTA DENPASAR',],
            ['id' => '5201', 'wil_province_id' => '52', 'name' => 'KAB. LOMBOK BARAT',],
            ['id' => '5202', 'wil_province_id' => '52', 'name' => 'KAB. LOMBOK TENGAH',],
            ['id' => '5203', 'wil_province_id' => '52', 'name' => 'KAB. LOMBOK TIMUR',],
            ['id' => '5204', 'wil_province_id' => '52', 'name' => 'KAB. SUMBAWA',],
            ['id' => '5205', 'wil_province_id' => '52', 'name' => 'KAB. DOMPU',],
            ['id' => '5206', 'wil_province_id' => '52', 'name' => 'KAB. BIMA',],
            ['id' => '5207', 'wil_province_id' => '52', 'name' => 'KAB. SUMBAWA BARAT',],
            ['id' => '5208', 'wil_province_id' => '52', 'name' => 'KAB. LOMBOK UTARA',],
            ['id' => '5271', 'wil_province_id' => '52', 'name' => 'KOTA MATARAM',],
            ['id' => '5272', 'wil_province_id' => '52', 'name' => 'KOTA BIMA',],
            ['id' => '5301', 'wil_province_id' => '53', 'name' => 'KAB. KUPANG',],
            ['id' => '5302', 'wil_province_id' => '53', 'name' => 'KAB TIMOR TENGAH SELATAN',],
            ['id' => '5303', 'wil_province_id' => '53', 'name' => 'KAB. TIMOR TENGAH UTARA',],
            ['id' => '5304', 'wil_province_id' => '53', 'name' => 'KAB. BELU',],
            ['id' => '5305', 'wil_province_id' => '53', 'name' => 'KAB. ALOR',],
            ['id' => '5306', 'wil_province_id' => '53', 'name' => 'KAB. FLORES TIMUR',],
            ['id' => '5307', 'wil_province_id' => '53', 'name' => 'KAB. SIKKA',],
            ['id' => '5308', 'wil_province_id' => '53', 'name' => 'KAB. ENDE',],
            ['id' => '5309', 'wil_province_id' => '53', 'name' => 'KAB. NGADA',],
            ['id' => '5310', 'wil_province_id' => '53', 'name' => 'KAB. MANGGARAI',],
            ['id' => '5311', 'wil_province_id' => '53', 'name' => 'KAB. SUMBA TIMUR',],
            ['id' => '5312', 'wil_province_id' => '53', 'name' => 'KAB. SUMBA BARAT',],
            ['id' => '5313', 'wil_province_id' => '53', 'name' => 'KAB. LEMBATA',],
            ['id' => '5314', 'wil_province_id' => '53', 'name' => 'KAB. ROTE NDAO',],
            ['id' => '5315', 'wil_province_id' => '53', 'name' => 'KAB. MANGGARAI BARAT',],
            ['id' => '5316', 'wil_province_id' => '53', 'name' => 'KAB. NAGEKEO',],
            ['id' => '5317', 'wil_province_id' => '53', 'name' => 'KAB. SUMBA TENGAH',],
            ['id' => '5318', 'wil_province_id' => '53', 'name' => 'KAB. SUMBA BARAT DAYA',],
            ['id' => '5319', 'wil_province_id' => '53', 'name' => 'KAB. MANGGARAI TIMUR',],
            ['id' => '5320', 'wil_province_id' => '53', 'name' => 'KAB. SABU RAIJUA',],
            ['id' => '5321', 'wil_province_id' => '53', 'name' => 'KAB. MALAKA',],
            ['id' => '5371', 'wil_province_id' => '53', 'name' => 'KOTA KUPANG',],
            ['id' => '6101', 'wil_province_id' => '61', 'name' => 'KAB. SAMBAS',],
            ['id' => '6102', 'wil_province_id' => '61', 'name' => 'KAB. MEMPAWAH',],
            ['id' => '6103', 'wil_province_id' => '61', 'name' => 'KAB. SANGGAU',],
            ['id' => '6104', 'wil_province_id' => '61', 'name' => 'KAB. KETAPANG',],
            ['id' => '6105', 'wil_province_id' => '61', 'name' => 'KAB. SINTANG',],
            ['id' => '6106', 'wil_province_id' => '61', 'name' => 'KAB. KAPUAS HULU',],
            ['id' => '6107', 'wil_province_id' => '61', 'name' => 'KAB. BENGKAYANG',],
            ['id' => '6108', 'wil_province_id' => '61', 'name' => 'KAB. LANDAK',],
            ['id' => '6109', 'wil_province_id' => '61', 'name' => 'KAB. SEKADAU',],
            ['id' => '6110', 'wil_province_id' => '61', 'name' => 'KAB. MELAWI',],
            ['id' => '6111', 'wil_province_id' => '61', 'name' => 'KAB. KAYONG UTARA',],
            ['id' => '6112', 'wil_province_id' => '61', 'name' => 'KAB. KUBU RAYA',],
            ['id' => '6171', 'wil_province_id' => '61', 'name' => 'KOTA PONTIANAK',],
            ['id' => '6172', 'wil_province_id' => '61', 'name' => 'KOTA SINGKAWANG',],
            ['id' => '6201', 'wil_province_id' => '62', 'name' => 'KAB. KOTAWARINGIN BARAT',],
            ['id' => '6202', 'wil_province_id' => '62', 'name' => 'KAB. KOTAWARINGIN TIMUR',],
            ['id' => '6203', 'wil_province_id' => '62', 'name' => 'KAB. KAPUAS',],
            ['id' => '6204', 'wil_province_id' => '62', 'name' => 'KAB. BARITO SELATAN',],
            ['id' => '6205', 'wil_province_id' => '62', 'name' => 'KAB. BARITO UTARA',],
            ['id' => '6206', 'wil_province_id' => '62', 'name' => 'KAB. KATINGAN',],
            ['id' => '6207', 'wil_province_id' => '62', 'name' => 'KAB. SERUYAN',],
            ['id' => '6208', 'wil_province_id' => '62', 'name' => 'KAB. SUKAMARA',],
            ['id' => '6209', 'wil_province_id' => '62', 'name' => 'KAB. LAMANDAU',],
            ['id' => '6210', 'wil_province_id' => '62', 'name' => 'KAB. GUNUNG MAS',],
            ['id' => '6211', 'wil_province_id' => '62', 'name' => 'KAB. PULANG PISAU',],
            ['id' => '6212', 'wil_province_id' => '62', 'name' => 'KAB. MURUNG RAYA',],
            ['id' => '6213', 'wil_province_id' => '62', 'name' => 'KAB. BARITO TIMUR',],
            ['id' => '6271', 'wil_province_id' => '62', 'name' => 'KOTA PALANGKARAYA',],
            ['id' => '6301', 'wil_province_id' => '63', 'name' => 'KAB. TANAH LAUT',],
            ['id' => '6302', 'wil_province_id' => '63', 'name' => 'KAB. KOTABARU',],
            ['id' => '6303', 'wil_province_id' => '63', 'name' => 'KAB. BANJAR',],
            ['id' => '6304', 'wil_province_id' => '63', 'name' => 'KAB. BARITO KUALA',],
            ['id' => '6305', 'wil_province_id' => '63', 'name' => 'KAB. TAPIN',],
            ['id' => '6306', 'wil_province_id' => '63', 'name' => 'KAB. HULU SUNGAI SELATAN',],
            ['id' => '6307', 'wil_province_id' => '63', 'name' => 'KAB. HULU SUNGAI TENGAH',],
            ['id' => '6308', 'wil_province_id' => '63', 'name' => 'KAB. HULU SUNGAI UTARA',],
            ['id' => '6309', 'wil_province_id' => '63', 'name' => 'KAB. TABALONG',],
            ['id' => '6310', 'wil_province_id' => '63', 'name' => 'KAB. TANAH BUMBU',],
            ['id' => '6311', 'wil_province_id' => '63', 'name' => 'KAB. BALANGAN',],
            ['id' => '6371', 'wil_province_id' => '63', 'name' => 'KOTA BANJARMASIN',],
            ['id' => '6372', 'wil_province_id' => '63', 'name' => 'KOTA BANJARBARU',],
            ['id' => '6401', 'wil_province_id' => '64', 'name' => 'KAB. PASER',],
            ['id' => '6402', 'wil_province_id' => '64', 'name' => 'KAB. KUTAI KARTANEGARA',],
            ['id' => '6403', 'wil_province_id' => '64', 'name' => 'KAB. BERAU',],
            ['id' => '6407', 'wil_province_id' => '64', 'name' => 'KAB. KUTAI BARAT',],
            ['id' => '6408', 'wil_province_id' => '64', 'name' => 'KAB. KUTAI TIMUR',],
            ['id' => '6409', 'wil_province_id' => '64', 'name' => 'KAB. PENAJAM PASER UTARA',],
            ['id' => '6411', 'wil_province_id' => '64', 'name' => 'KAB. MAHAKAM ULU',],
            ['id' => '6471', 'wil_province_id' => '64', 'name' => 'KOTA BALIKPAPAN',],
            ['id' => '6472', 'wil_province_id' => '64', 'name' => 'KOTA SAMARINDA',],
            ['id' => '6474', 'wil_province_id' => '64', 'name' => 'KOTA BONTANG',],
            ['id' => '6501', 'wil_province_id' => '65', 'name' => 'KAB. BULUNGAN',],
            ['id' => '6502', 'wil_province_id' => '65', 'name' => 'KAB. MALINAU',],
            ['id' => '6503', 'wil_province_id' => '65', 'name' => 'KAB. NUNUKAN',],
            ['id' => '6504', 'wil_province_id' => '65', 'name' => 'KAB. TANA TIDUNG',],
            ['id' => '6571', 'wil_province_id' => '65', 'name' => 'KOTA TARAKAN',],
            ['id' => '7101', 'wil_province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW',],
            ['id' => '7102', 'wil_province_id' => '71', 'name' => 'KAB. MINAHASA',],
            ['id' => '7103', 'wil_province_id' => '71', 'name' => 'KAB. KEPULAUAN SANGIHE',],
            ['id' => '7104', 'wil_province_id' => '71', 'name' => 'KAB. KEPULAUAN TALAUD',],
            ['id' => '7105', 'wil_province_id' => '71', 'name' => 'KAB. MINAHASA SELATAN',],
            ['id' => '7106', 'wil_province_id' => '71', 'name' => 'KAB. MINAHASA UTARA',],
            ['id' => '7107', 'wil_province_id' => '71', 'name' => 'KAB. MINAHASA TENGGARA',],
            ['id' => '7108', 'wil_province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW UTARA',],
            ['id' => '7109', 'wil_province_id' => '71', 'name' => 'KAB. KEP. SIAU TAGULANDANG BIARO',],
            ['id' => '7110', 'wil_province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW TIMUR',],
            ['id' => '7111', 'wil_province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW SELATAN',],
            ['id' => '7171', 'wil_province_id' => '71', 'name' => 'KOTA MANADO',],
            ['id' => '7172', 'wil_province_id' => '71', 'name' => 'KOTA BITUNG',],
            ['id' => '7173', 'wil_province_id' => '71', 'name' => 'KOTA TOMOHON',],
            ['id' => '7174', 'wil_province_id' => '71', 'name' => 'KOTA KOTAMOBAGU',],
            ['id' => '7201', 'wil_province_id' => '72', 'name' => 'KAB. BANGGAI',],
            ['id' => '7202', 'wil_province_id' => '72', 'name' => 'KAB. POSO',],
            ['id' => '7203', 'wil_province_id' => '72', 'name' => 'KAB. DONGGALA',],
            ['id' => '7204', 'wil_province_id' => '72', 'name' => 'KAB. TOLI TOLI',],
            ['id' => '7205', 'wil_province_id' => '72', 'name' => 'KAB. BUOL',],
            ['id' => '7206', 'wil_province_id' => '72', 'name' => 'KAB. MOROWALI',],
            ['id' => '7207', 'wil_province_id' => '72', 'name' => 'KAB. BANGGAI KEPULAUAN',],
            ['id' => '7208', 'wil_province_id' => '72', 'name' => 'KAB. PARIGI MOUTONG',],
            ['id' => '7209', 'wil_province_id' => '72', 'name' => 'KAB. TOJO UNA UNA',],
            ['id' => '7210', 'wil_province_id' => '72', 'name' => 'KAB. SIGI',],
            ['id' => '7211', 'wil_province_id' => '72', 'name' => 'KAB. BANGGAI LAUT',],
            ['id' => '7212', 'wil_province_id' => '72', 'name' => 'KAB. MOROWALI UTARA',],
            ['id' => '7271', 'wil_province_id' => '72', 'name' => 'KOTA PALU',],
            ['id' => '7301', 'wil_province_id' => '73', 'name' => 'KAB. KEPULAUAN SELAYAR',],
            ['id' => '7302', 'wil_province_id' => '73', 'name' => 'KAB. BULUKUMBA',],
            ['id' => '7303', 'wil_province_id' => '73', 'name' => 'KAB. BANTAENG',],
            ['id' => '7304', 'wil_province_id' => '73', 'name' => 'KAB. JENEPONTO',],
            ['id' => '7305', 'wil_province_id' => '73', 'name' => 'KAB. TAKALAR',],
            ['id' => '7306', 'wil_province_id' => '73', 'name' => 'KAB. GOWA',],
            ['id' => '7307', 'wil_province_id' => '73', 'name' => 'KAB. SINJAI',],
            ['id' => '7308', 'wil_province_id' => '73', 'name' => 'KAB. BONE',],
            ['id' => '7309', 'wil_province_id' => '73', 'name' => 'KAB. MAROS',],
            ['id' => '7310', 'wil_province_id' => '73', 'name' => 'KAB. PANGKAJENE KEPULAUAN',],
            ['id' => '7311', 'wil_province_id' => '73', 'name' => 'KAB. BARRU',],
            ['id' => '7312', 'wil_province_id' => '73', 'name' => 'KAB. SOPPENG',],
            ['id' => '7313', 'wil_province_id' => '73', 'name' => 'KAB. WAJO',],
            ['id' => '7314', 'wil_province_id' => '73', 'name' => 'KAB. SIDENRENG RAPPANG',],
            ['id' => '7315', 'wil_province_id' => '73', 'name' => 'KAB. PINRANG',],
            ['id' => '7316', 'wil_province_id' => '73', 'name' => 'KAB. ENREKANG',],
            ['id' => '7317', 'wil_province_id' => '73', 'name' => 'KAB. LUWU',],
            ['id' => '7318', 'wil_province_id' => '73', 'name' => 'KAB. TANA TORAJA',],
            ['id' => '7322', 'wil_province_id' => '73', 'name' => 'KAB. LUWU UTARA',],
            ['id' => '7324', 'wil_province_id' => '73', 'name' => 'KAB. LUWU TIMUR',],
            ['id' => '7326', 'wil_province_id' => '73', 'name' => 'KAB. TORAJA UTARA',],
            ['id' => '7371', 'wil_province_id' => '73', 'name' => 'KOTA MAKASSAR',],
            ['id' => '7372', 'wil_province_id' => '73', 'name' => 'KOTA PARE PARE',],
            ['id' => '7373', 'wil_province_id' => '73', 'name' => 'KOTA PALOPO',],
            ['id' => '7401', 'wil_province_id' => '74', 'name' => 'KAB. KOLAKA',],
            ['id' => '7402', 'wil_province_id' => '74', 'name' => 'KAB. KONAWE',],
            ['id' => '7403', 'wil_province_id' => '74', 'name' => 'KAB. MUNA',],
            ['id' => '7404', 'wil_province_id' => '74', 'name' => 'KAB. BUTON',],
            ['id' => '7405', 'wil_province_id' => '74', 'name' => 'KAB. KONAWE SELATAN',],
            ['id' => '7406', 'wil_province_id' => '74', 'name' => 'KAB. BOMBANA',],
            ['id' => '7407', 'wil_province_id' => '74', 'name' => 'KAB. WAKATOBI',],
            ['id' => '7408', 'wil_province_id' => '74', 'name' => 'KAB. KOLAKA UTARA',],
            ['id' => '7409', 'wil_province_id' => '74', 'name' => 'KAB. KONAWE UTARA',],
            ['id' => '7410', 'wil_province_id' => '74', 'name' => 'KAB. BUTON UTARA',],
            ['id' => '7411', 'wil_province_id' => '74', 'name' => 'KAB. KOLAKA TIMUR',],
            ['id' => '7412', 'wil_province_id' => '74', 'name' => 'KAB. KONAWE KEPULAUAN',],
            ['id' => '7413', 'wil_province_id' => '74', 'name' => 'KAB. MUNA BARAT',],
            ['id' => '7414', 'wil_province_id' => '74', 'name' => 'KAB. BUTON TENGAH',],
            ['id' => '7415', 'wil_province_id' => '74', 'name' => 'KAB. BUTON SELATAN',],
            ['id' => '7471', 'wil_province_id' => '74', 'name' => 'KOTA KENDARI',],
            ['id' => '7472', 'wil_province_id' => '74', 'name' => 'KOTA BAU BAU',],
            ['id' => '7501', 'wil_province_id' => '75', 'name' => 'KAB. GORONTALO',],
            ['id' => '7502', 'wil_province_id' => '75', 'name' => 'KAB. BOALEMO',],
            ['id' => '7503', 'wil_province_id' => '75', 'name' => 'KAB. BONE BOLANGO',],
            ['id' => '7504', 'wil_province_id' => '75', 'name' => 'KAB. POHUWATO',],
            ['id' => '7505', 'wil_province_id' => '75', 'name' => 'KAB. GORONTALO UTARA',],
            ['id' => '7571', 'wil_province_id' => '75', 'name' => 'KOTA GORONTALO',],
            ['id' => '7601', 'wil_province_id' => '76', 'name' => 'KAB. PASANGKAYU',],
            ['id' => '7602', 'wil_province_id' => '76', 'name' => 'KAB. MAMUJU',],
            ['id' => '7603', 'wil_province_id' => '76', 'name' => 'KAB. MAMASA',],
            ['id' => '7604', 'wil_province_id' => '76', 'name' => 'KAB. POLEWALI MANDAR',],
            ['id' => '7605', 'wil_province_id' => '76', 'name' => 'KAB. MAJENE',],
            ['id' => '7606', 'wil_province_id' => '76', 'name' => 'KAB. MAMUJU TENGAH',],
            ['id' => '8101', 'wil_province_id' => '81', 'name' => 'KAB. MALUKU TENGAH',],
            ['id' => '8102', 'wil_province_id' => '81', 'name' => 'KAB. MALUKU TENGGARA',],
            ['id' => '8103', 'wil_province_id' => '81', 'name' => 'KAB. KEPULAUAN TANIMBAR',],
            ['id' => '8104', 'wil_province_id' => '81', 'name' => 'KAB. BURU',],
            ['id' => '8105', 'wil_province_id' => '81', 'name' => 'KAB. SERAM BAGIAN TIMUR',],
            ['id' => '8106', 'wil_province_id' => '81', 'name' => 'KAB. SERAM BAGIAN BARAT',],
            ['id' => '8107', 'wil_province_id' => '81', 'name' => 'KAB. KEPULAUAN ARU',],
            ['id' => '8108', 'wil_province_id' => '81', 'name' => 'KAB. MALUKU BARAT DAYA',],
            ['id' => '8109', 'wil_province_id' => '81', 'name' => 'KAB. BURU SELATAN',],
            ['id' => '8171', 'wil_province_id' => '81', 'name' => 'KOTA AMBON',],
            ['id' => '8172', 'wil_province_id' => '81', 'name' => 'KOTA TUAL',],
            ['id' => '8201', 'wil_province_id' => '82', 'name' => 'KAB. HALMAHERA BARAT',],
            ['id' => '8202', 'wil_province_id' => '82', 'name' => 'KAB. HALMAHERA TENGAH',],
            ['id' => '8203', 'wil_province_id' => '82', 'name' => 'KAB. HALMAHERA UTARA',],
            ['id' => '8204', 'wil_province_id' => '82', 'name' => 'KAB. HALMAHERA SELATAN',],
            ['id' => '8205', 'wil_province_id' => '82', 'name' => 'KAB. KEPULAUAN SULA',],
            ['id' => '8206', 'wil_province_id' => '82', 'name' => 'KAB. HALMAHERA TIMUR',],
            ['id' => '8207', 'wil_province_id' => '82', 'name' => 'KAB. PULAU MOROTAI',],
            ['id' => '8208', 'wil_province_id' => '82', 'name' => 'KAB. PULAU TALIABU',],
            ['id' => '8271', 'wil_province_id' => '82', 'name' => 'KOTA TERNATE',],
            ['id' => '8272', 'wil_province_id' => '82', 'name' => 'KOTA TIDORE KEPULAUAN',],
            ['id' => '9103', 'wil_province_id' => '91', 'name' => 'KAB. JAYAPURA',],
            ['id' => '9105', 'wil_province_id' => '91', 'name' => 'KAB. KEPULAUAN YAPEN',],
            ['id' => '9106', 'wil_province_id' => '91', 'name' => 'KAB. BIAK NUMFOR',],
            ['id' => '9110', 'wil_province_id' => '91', 'name' => 'KAB. SARMI',],
            ['id' => '9111', 'wil_province_id' => '91', 'name' => 'KAB. KEEROM',],
            ['id' => '9115', 'wil_province_id' => '91', 'name' => 'KAB. WAROPEN',],
            ['id' => '9119', 'wil_province_id' => '91', 'name' => 'KAB. SUPIORI',],
            ['id' => '9120', 'wil_province_id' => '91', 'name' => 'KAB. MAMBERAMO RAYA',],
            ['id' => '9171', 'wil_province_id' => '91', 'name' => 'KOTA JAYAPURA',],
            ['id' => '9201', 'wil_province_id' => '92', 'name' => 'KAB. SORONG',],
            ['id' => '9202', 'wil_province_id' => '92', 'name' => 'KAB. MANOKWARI',],
            ['id' => '9203', 'wil_province_id' => '92', 'name' => 'KAB. FAK FAK',],
            ['id' => '9204', 'wil_province_id' => '92', 'name' => 'KAB. SORONG SELATAN',],
            ['id' => '9205', 'wil_province_id' => '92', 'name' => 'KAB. RAJA AMPAT',],
            ['id' => '9206', 'wil_province_id' => '92', 'name' => 'KAB. TELUK BINTUNI',],
            ['id' => '9207', 'wil_province_id' => '92', 'name' => 'KAB. TELUK WONDAMA',],
            ['id' => '9208', 'wil_province_id' => '92', 'name' => 'KAB. KAIMANA',],
            ['id' => '9209', 'wil_province_id' => '92', 'name' => 'KAB. TAMBRAUW',],
            ['id' => '9210', 'wil_province_id' => '92', 'name' => 'KAB. MAYBRAT',],
            ['id' => '9211', 'wil_province_id' => '92', 'name' => 'KAB. MANOKWARI SELATAN',],
            ['id' => '9212', 'wil_province_id' => '92', 'name' => 'KAB. PEGUNUNGAN ARFAK',],
            ['id' => '9271', 'wil_province_id' => '92', 'name' => 'KOTA SORONG',],
            ['id' => '9301', 'wil_province_id' => '93', 'name' => 'KAB. MERAUKE',],
            ['id' => '9302', 'wil_province_id' => '93', 'name' => 'KAB. BOVEN DIGOEL',],
            ['id' => '9303', 'wil_province_id' => '93', 'name' => 'KAB. MAPPI',],
            ['id' => '9304', 'wil_province_id' => '93', 'name' => 'KAB. ASMAT',],
            ['id' => '9401', 'wil_province_id' => '94', 'name' => 'KAB. NABIRE',],
            ['id' => '9402', 'wil_province_id' => '94', 'name' => 'KAB. PUNCAK JAYA',],
            ['id' => '9403', 'wil_province_id' => '94', 'name' => 'KAB. PANIAI',],
            ['id' => '9404', 'wil_province_id' => '94', 'name' => 'KAB. MIMIKA',],
            ['id' => '9405', 'wil_province_id' => '94', 'name' => 'KAB. PUNCAK',],
            ['id' => '9406', 'wil_province_id' => '94', 'name' => 'KAB. DOGIYAI',],
            ['id' => '9407', 'wil_province_id' => '94', 'name' => 'KAB. INTAN JAYA',],
            ['id' => '9408', 'wil_province_id' => '94', 'name' => 'KAB. DEIYAI',],
            ['id' => '9501', 'wil_province_id' => '95', 'name' => 'KAB. JAYAWIJAYA',],
            ['id' => '9502', 'wil_province_id' => '95', 'name' => 'KAB. PEGUNUNGAN BINTANG',],
            ['id' => '9503', 'wil_province_id' => '95', 'name' => 'KAB. YAHUKIMO',],
            ['id' => '9504', 'wil_province_id' => '95', 'name' => 'KAB. TOLIKARA',],
            ['id' => '9505', 'wil_province_id' => '95', 'name' => 'KAB. MAMBERAMO TENGAH',],
            ['id' => '9506', 'wil_province_id' => '95', 'name' => 'KAB. YALIMO',],
            ['id' => '9507', 'wil_province_id' => '95', 'name' => 'KAB. LANNY JAYA',],
            ['id' => '9508', 'wil_province_id' => '95', 'name' => 'KAB. NDUGA',],
        ];

        foreach ($wil_cities as $key => $wil_city) {
            WilCity::create($wil_city);

            echo $key . ' | ' . $wil_city['id'] . ' | ' . $wil_city['name'] . PHP_EOL;
        }
    }
}
